" Make secure ...
set nobackup
set noswapfile
set noundofile

" Show line numbers ...
set number

" Highlight matching brackets ...
set showmatch

" Highlight word wrap marker ...
set colorcolumn=80

" Enable syntax highlighting ...
syntax on

" Sort out tabs ...
set expandtab
set tabstop=4

" Don't be clever when selecting text with the mouse ...
set mouse-=a
