#!/usr/bin/env bash

# Change directory ...
cd "$HOME/Repositories" || exit 1

# Loop over repositories ...
for d in */.git; do
    # Change directory ...
    cd "$(dirname "$d")" || exit 1

    # Commit everything ...
    git commit -a

    # Change directory ...
    cd ../
done
