#!/usr/bin/env bash

# Change directory ...
cd "$HOME/Repositories" || exit 1

# Loop over repositories ...
for d in */.git; do
    # Change directory ...
    cd "$(dirname "$d")" || exit 1

    # Pull everything ...
    git pull --recurse-submodules

    # Change directory ...
    cd ../
done
