#!/usr/bin/env bash

# Change directory ...
cd "$HOME/Repositories" || exit 1

# Loop over repositories ...
for d in */.git; do
    # Change directory ...
    cd "$(dirname "$d")" || exit 1

    # Print the remotes ...
    git remote -v

    # Change directory ...
    cd ../
done
